info:
  contact:
    email: svk@codecowboydotio
    name: API Support
  description: Swagger API for Golang Project for git rest api
  license:
    name: MIT
    url: https://github.com/codecowboydotio/go-rest-api/blob/main/LICENSE
  termsOfService: http://swagger.io/terms/
  title: GO Rest API Swagger API
  version: "1.0"
paths:
  /:
    post:
      consumes:
      - '*/*'
      description: Pull a github repository down.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Pull a github repository down.
      tags:
      - root
swagger: "2.0"
